import { fileURLToPath } from "url";
import pool from "./index.js";

const quizData = [
  {
    topic_id: 26, // Networking Fundamentals
    questions: [
      { q: "What does 'IP' stand for in networking?", o: {A: "Internal Protocol", B: "Internet Protocol", C: "Intranet Port", D: "Instant Packet"}, c: "B", e: "IP is the set of rules governing the format of data sent via the internet." },
      { q: "Which protocol is 'connectionless' and faster but less reliable?", o: {A: "TCP", B: "UDP", C: "HTTP", D: "SSH"}, c: "B", e: "UDP is often used for streaming and gaming where speed is priority." },
      { q: "What is the purpose of 'DNS'?", o: {A: "To encrypt data", B: "To translate domain names (google.com) into IP addresses", C: "To assign IPs to local machines", D: "To block viruses"}, c: "B", e: "DNS is like the phonebook of the internet." },
      { q: "What is a 'MAC Address'?", o: {A: "An address for Apple computers only", B: "A unique physical identifier for a network interface card", C: "A type of software", D: "A dynamic IP address"}, c: "B", e: "MAC addresses are permanent hardware IDs." },
      { q: "Which layer of the OSI model is responsible for routing packets?", o: {A: "Data Link", B: "Network Layer (Layer 3)", C: "Transport", D: "Application"}, c: "B", e: "Routers operate at the Network Layer using IP addresses." },
      { q: "What does 'HTTP' status code 404 mean?", o: {A: "Success", B: "Server Error", C: "Not Found", D: "Unauthorized"}, c: "C", e: "404 indicates the requested resource could not be found." },
      { q: "What is a 'Subnet Mask' used for?", o: {A: "To hide the IP", B: "To define which part of an IP is the network and which is the host", C: "To increase speed", D: "To secure the router"}, c: "B", e: "Subnetting allows efficient network organization." },
      { q: "What is 'DHCP'?", o: {A: "A type of firewall", B: "A protocol that automatically assigns IP addresses to devices on a network", C: "A web browser", D: "A domain provider"}, c: "B", e: "DHCP simplifies network management by automating IP assignment." },
      { q: "What is a 'Firewall'?", o: {A: "A physical wall", B: "A security system that monitors and controls incoming/outgoing network traffic", C: "A type of fast cable", D: "A database server"}, c: "B", e: "Firewalls act as a barrier between trusted and untrusted networks." },
      { q: "Which port is standard for HTTPS?", o: {A: "80", B: "21", C: "443", D: "22"}, c: "C", e: "Port 80 is for HTTP (unsecured); 443 is for HTTPS (secured)." }
    ]
  },
  {
    topic_id: 27, // Docker and Containers
    questions: [
      { q: "What is a 'Docker Image'?", o: {A: "A picture of a whale", B: "A lightweight, standalone, executable package of software", C: "A running process", D: "A cloud server"}, c: "B", e: "Images are the templates used to create containers." },
      { q: "What is a 'Docker Container'?", o: {A: "A shipping box", B: "A runtime instance of a Docker Image", C: "A storage unit for code", D: "A type of virtual machine"}, c: "B", e: "Containers run the actual application code in an isolated environment." },
      { q: "Which file is used to define the steps to build a Docker Image?", o: {A: "DockerConfig", B: "Dockerfile", C: "DockerCompose.yml", D: "build.sh"}, c: "B", e: "Dockerfiles contain the instructions for creating an image." },
      { q: "What is the benefit of containers over Virtual Machines?", o: {A: "They are larger", B: "They share the host OS kernel and are much more lightweight", C: "They are more expensive", D: "They only run on Linux"}, c: "B", e: "Containers start faster and use fewer resources than VMs." },
      { q: "What does 'Docker Hub' provide?", o: {A: "A local database", B: "A public registry for sharing and finding Docker images", C: "A web hosting service", D: "A code editor"}, c: "B", e: "Hub is the default registry for Docker." },
      { q: "What is 'Docker Compose' used for?", o: {A: "Editing code", B: "Defining and running multi-container Docker applications", C: "Monitoring CPU usage", D: "Creating single containers only"}, c: "B", e: "Compose uses YAML files to configure application services." },
      { q: "What is a 'Volume' in Docker?", o: {A: "The sound level", B: "A mechanism for persisting data generated by and used by containers", C: "A type of network", D: "A CPU limit"}, c: "B", e: "Volumes keep data safe even if a container is deleted." },
      { q: "What command builds an image from a Dockerfile?", o: {A: "docker run", B: "docker build", C: "docker create", D: "docker init"}, c: "B", e: "docker build converts a Dockerfile into an image." },
      { q: "What is 'Orchestration' in the context of containers?", o: {A: "Writing music", B: "Managing the lifecycle of containers, including scaling and networking", C: "Deleting images", D: "Installing Docker"}, c: "B", e: "Orchestrators (like Kubernetes) automate container management at scale." },
      { q: "Which command stops a running container?", o: {A: "docker del", B: "docker stop", C: "docker end", D: "docker pause"}, c: "B", e: "docker stop sends a SIGTERM to the container." }
    ]
  },
  {
    topic_id: 28, // CI/CD Pipelines
    questions: [
      { q: "What does 'CI' stand for in CI/CD?", o: {A: "Continuous Improvement", B: "Continuous Integration", C: "Code Integration", D: "Computer Intelligence"}, c: "B", e: "CI is the practice of frequently merging code changes into a central repository." },
      { q: "What does 'CD' most commonly stand for?", o: {A: "Continuous Data", B: "Continuous Delivery / Continuous Deployment", C: "Code Deployment", D: "Central Distribution"}, c: "B", e: "CD automates the release process after integration." },
      { q: "What is the main goal of a CI pipeline?", o: {A: "To write code", B: "To automatically build and test code changes early", C: "To replace developers", D: "To store documentation"}, c: "B", e: "CI ensures code is always in a releasable state." },
      { q: "What is a 'Pipeline'?", o: {A: "A physical pipe", B: "A set of automated processes that allow developers to reliably move code from commit to production", C: "A type of database", D: "A Jira ticket"}, c: "B", e: "Pipelines consist of stages like Build, Test, and Deploy." },
      { q: "What is the difference between Continuous Delivery and Continuous Deployment?", o: {A: "No difference", B: "Delivery requires manual approval to go to production; Deployment is automatic", C: "Deployment is slower", D: "Delivery is for small teams only"}, c: "B", e: "Deployment removes the human bottleneck for the final release." },
      { q: "What is a 'Runner' or 'Agent' in CI/CD?", o: {A: "A fast coder", B: "A machine or container that executes the jobs defined in the pipeline", C: "A security tool", D: "A database query"}, c: "B", e: "Runners do the actual work of building and testing." },
      { q: "Which tool is a popular open-source automation server for CI/CD?", o: {A: "React", B: "Jenkins", C: "MongoDB", D: "VS Code"}, c: "B", e: "Jenkins is a long-standing industry standard for automation." },
      { q: "What is 'Infrastructure as Code' (IaC)?", o: {A: "Writing code manually on a server", B: "Managing and provisioning infrastructure through machine-readable definition files", C: "Printing code on paper", D: "A type of cloud storage"}, c: "B", e: "IaC tools like Terraform and CloudFormation bring CI/CD benefits to infrastructure." },
      { q: "What is a 'Smoke Test' in a pipeline?", o: {A: "Testing if the server is hot", B: "A quick set of tests to ensure the most critical functions work after a build", C: "Testing image quality", D: "A manual security audit"}, c: "B", e: "Smoke tests provide rapid feedback on the build's basic stability." },
      { q: "Why is 'Automated Testing' crucial for CD?", o: {A: "It's not", B: "To ensure that automated releases don't introduce regressions or bugs", C: "To make developers work less", D: "To use more CPU"}, c: "B", e: "Automation is only as good as the tests that validate it." }
    ]
  },
  {
    topic_id: 29, // Kubernetes
    questions: [
      { q: "What is Kubernetes (K8s)?", o: {A: "A programming language", B: "An open-source platform for automating deployment, scaling, and management of containerized apps", C: "A cloud provider", D: "A type of Docker image"}, c: "B", e: "Kubernetes is the industry standard for container orchestration." },
      { q: "What is a 'Pod' in Kubernetes?", o: {A: "A group of servers", B: "The smallest deployable unit that can contain one or more containers", C: "A database table", D: "A type of network cable"}, c: "B", e: "Containers in a Pod share the same network and storage resources." },
      { q: "What does the 'kubelet' do?", o: {A: "It's a small pod", B: "An agent that runs on each node in the cluster and ensures containers are running in a Pod", C: "It manages user logins", D: "It's the CLI tool"}, c: "B", e: "Kubelet is the 'worker' agent on every node." },
      { q: "What is a 'Node' in K8s?", o: {A: "A single container", B: "A worker machine (physical or virtual) that runs the pods", C: "A JavaScript library", D: "A type of service"}, c: "B", e: "Nodes provide the resources (CPU, RAM) for the cluster." },
      { q: "What is a 'Service' in Kubernetes?", o: {A: "A customer support tool", B: "An abstraction that defines a logical set of Pods and a policy to access them", C: "A background task", D: "A cloud bill"}, c: "B", e: "Services provide stable IP addresses and load balancing for dynamic Pods." },
      { q: "What is 'kubectl'?", o: {A: "The K8s server", B: "The command-line tool for interacting with Kubernetes clusters", C: "A type of container", D: "A monitoring dashboard"}, c: "B", e: "kubectl is used to deploy, inspect, and manage cluster resources." },
      { q: "What is a 'Namespace'?", o: {A: "A domain name", B: "A way to divide cluster resources between multiple users or projects", C: "A type of variable", D: "A security certificate"}, c: "B", e: "Namespaces provide virtual isolation within a single cluster." },
      { q: "What is 'Self-healing' in Kubernetes?", o: {A: "The system fixing its own bugs", B: "K8s automatically restarting failed containers or replacing dead nodes", C: "A programmer getting more sleep", D: "A manual backup process"}, c: "B", e: "Kubernetes ensures the desired state of the cluster is maintained." },
      { q: "What is an 'Ingress'?", o: {A: "A way to exit the cluster", B: "An API object that manages external access to the services (usually HTTP)", C: "A type of secret", D: "A database query"}, c: "B", e: "Ingress acts as a smart router/load balancer for the cluster." },
      { q: "What is a 'Deployment'?", o: {A: "Deleting a pod", B: "An object that manages a replicated application, providing declarative updates", C: "A single container run", D: "A type of cloud account"}, c: "B", e: "Deployments allow for rolling updates and rollbacks." }
    ]
  },
  {
    topic_id: 30, // Monitoring and Observability
    questions: [
      { q: "What is the difference between Monitoring and Observability?", o: {A: "No difference", B: "Monitoring tells you something is wrong; Observability helps you understand WHY it's wrong", C: "Monitoring is for hardware only", D: "Observability is more expensive"}, c: "B", e: "Observability uses logs, metrics, and traces to provide deep insights." },
      { q: "What are 'Metrics'?", o: {A: "Written descriptions of errors", B: "Numerical data points measured over time (CPU, RAM, RPS)", C: "A list of users", D: "Source code files"}, c: "B", e: "Metrics help in identifying trends and setting alerts." },
      { q: "What is 'Distributed Tracing'?", o: {A: "Drawing a map", B: "Tracking a single request as it travels through multiple microservices", C: "Recording video of the screen", D: "Checking the database size"}, c: "B", e: "Tracing is essential for identifying bottlenecks in complex systems." },
      { q: "What is a 'Log'?", o: {A: "A piece of wood", B: "A text-based record of an event that happened in the application", C: "A mathematical function", D: "A type of database index"}, c: "B", e: "Logs provide a detailed history of system actions and errors." },
      { q: "What is an 'Alert' in monitoring?", o: {A: "A user complaint", B: "An automated notification triggered when a metric crosses a threshold", C: "A system crash", D: "A new feature release"}, c: "B", e: "Alerts ensure that issues are noticed quickly." },
      { q: "Which tool is a popular open-source time-series database and alerting toolkit?", o: {A: "React", B: "Prometheus", C: "PostgreSQL", D: "Docker"}, c: "B", e: "Prometheus is widely used for monitoring containerized environments." },
      { q: "What is a 'Dashboard' in monitoring?", o: {A: "The car's console", B: "A visual display of the most important metrics and system status", C: "A type of login screen", D: "A code editor"}, c: "B", e: "Dashboards (like Grafana) provide at-a-glance visibility." },
      { q: "What does 'SLA' stand for?", o: {A: "System Log Archive", B: "Service Level Agreement", C: "Simple Level Access", D: "Standard Link API"}, c: "B", e: "An SLA is a commitment between a service provider and a client." },
      { q: "What is the 'Golden Signals' of monitoring?", o: {A: "Red, Green, Yellow", B: "Latency, Traffic, Errors, and Saturation", C: "CPU, RAM, Disk, Network", D: "Speed, Cost, Security"}, c: "B", e: "These four signals are key to monitoring user-facing systems." },
      { q: "What is 'Log Aggregation'?", o: {A: "Deleting logs", B: "Collecting logs from all sources into a single, searchable central location", C: "Summarizing logs by hand", D: "A type of encryption"}, c: "B", e: "Log Aggregation tools help developers find errors across many servers." }
    ]
  },
  {
    topic_id: 31, // Cloud Platforms AWS
    questions: [
      { q: "What is Amazon EC2?", o: {A: "A cloud database", B: "Virtual servers in the cloud", C: "A storage service", D: "A machine learning tool"}, c: "B", e: "EC2 (Elastic Compute Cloud) provides resizable compute capacity." },
      { q: "What is 'Amazon S3' primarily used for?", o: {A: "Running code", B: "Object storage (files, images, backups)", C: "Sending emails", D: "Managing databases"}, c: "B", e: "S3 (Simple Storage Service) is highly durable and scalable." },
      { q: "What is 'AWS Lambda'?", o: {A: "A physical server", B: "A serverless compute service that runs code in response to events", C: "A type of virtual network", D: "A database engine"}, c: "B", e: "Lambda allows you to run code without provisioning servers." },
      { q: "What is 'Amazon RDS'?", o: {A: "A fast router", B: "A managed relational database service", C: "A storage volume", D: "A security group"}, c: "B", e: "RDS simplifies setting up, operating, and scaling databases (SQL)." },
      { q: "What does 'IAM' stand for in AWS?", o: {A: "Internal Access Management", B: "Identity and Access Management", C: "Instant Account Manager", D: "Internet AWS Monitor"}, c: "B", e: "IAM is used to securely control access to AWS resources." },
      { q: "What is a 'Region' in AWS?", o: {A: "A single data center", B: "A physical location in the world where multiple Availability Zones are grouped", C: "A type of cloud bill", D: "A network setting"}, c: "B", e: "Deploying across regions provides the highest level of fault tolerance." },
      { q: "What is 'Amazon VPC'?", o: {A: "A virtual private server", B: "A virtual network dedicated to your AWS account", C: "A type of database", D: "A coding tool"}, c: "B", e: "VPC allows you to launch AWS resources into a virtual network you've defined." },
      { q: "What is 'Amazon DynamoDB'?", o: {A: "A relational database", B: "A fully managed NoSQL key-value and document database", C: "A storage service", D: "A serverless compute service"}, c: "B", e: "DynamoDB is designed for high-scale, low-latency applications." },
      { q: "What is 'AWS CloudFormation' used for?", o: {A: "Editing images", B: "Provisioning infrastructure using code (IaC)", C: "Monitoring CPU", D: "Managing user accounts"}, c: "B", e: "CloudFormation automates the setup of AWS resources." },
      { q: "What is 'Amazon CloudWatch'?", o: {A: "A clock service", B: "A monitoring and observability service for AWS resources", C: "A type of firewall", D: "A domain provider"}, c: "B", e: "CloudWatch provides metrics, logs, and alerts for AWS services." }
    ]
  }
];

export const insertManualQuizDataBatch5 = async () => {
  try {
    const check = await pool.query("SELECT COUNT(*) FROM topic_quiz_questions WHERE topic_id IN (26,27,28,29,30,31)");
    if (parseInt(check.rows[0].count) > 0) {
      console.log("⏩ Batch 5 quiz data already exists. Skipping.");
      return;
    }

    for (const topic of quizData) {
      console.log(`Inserting questions for topic ${topic.topic_id}...`);
      for (const q of topic.questions) {
        await pool.query(
          `INSERT INTO topic_quiz_questions 
           (topic_id, question, options, correct_option, explanation)
           VALUES ($1, $2, $3, $4, $5)`,
          [topic.topic_id, q.q, JSON.stringify(q.o), q.c, q.e]
        );
      }
    }
    console.log("✅ Batch 5 Inserted!");
  } catch (err) {
    console.error("❌ Batch 5 Insertion failed:", err);
    throw err;
  }
};

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  insertManualQuizDataBatch5()
    .then(() => process.exit(0))
    .catch(() => process.exit(1));
}
